services:
  date:
    image: progeattt/result-date
    build:
      dockerfile: date.dockerfile
  result:
    image: progeattt/result
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - date
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsnecrypt
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsnecrypt
